### PR TITLE
Taskbar, Css and bug fixes

### LINKED ISSUE #117: Task 57: Update taskbar/admin taskbar to show what page the user is on (frontend)
Either an underline or a colored bubble to just tell the user what page they are on

- [x] show what page they are on using the navbar

### PR DESCRIPTION
**Pull request by jlaksana**
Navbar shows what page the user is at. Fixed CSS bugs on login page. Put a try catch in isAdmin endpoint because the backend kept crashing when switching between login and signup pages.

### CODE REVIEW

File: backend/src/getUsers.js [hunk 1]
```diff
@@ -83,7 +83,11 @@ router.post('/isAdmin', async (req, res) => {
     }
   }).catch((err) => {
     console.log(err);
-    res.status(404).send(err);
+    try {
```
Comment (mw1510) [inline backend/src/getUsers.js]: In the isAdmin endpoint can't take in a token in the beginning if the user isn't logged in since there is no valid token to verify.

**Review by mw1510 — CHANGES_REQUESTED** [review]

File: backend/src/getUsers.js (hunk 1 above)
Comment (mw1510) [reply backend/src/getUsers.js]: Screen Shot 2022-05-26 at 9 22 39 AM
Screen Shot 2022-05-26 at 9 23 05 AM
Can we change the underline to be across the whole text and not cut off? I think we should also change the color to that dark blue that the Woods Humane Society logo has

Comment (mw1510) [reply backend/src/getUsers.js]: For the isAdmin endpoint since there isn't a valid token to check when the user is logging in or signing up, we should maybe check localStorage for a valid token before we send it or just delete it entirely

Comment (jlaksana) [reply backend/src/getUsers.js]: See latest commit!

**Review by mw1510 — APPROVED** [review]
